In [5]:
import numpy as np

class DenseLayer:
    """
    A class representing a single, fully-connected (dense) layer in a neural network.
    """
    def __init__(self, n_inputs, n_neurons):
        """
        Initializes the layer's weights and biases.
        
        Parameters:
        n_inputs (int): The number of input features (i.e., the size of the previous layer).
        n_neurons (int): The number of neurons in this layer.
        """
        # Initialize weights with small random values. Shape: (n_inputs, n_neurons).
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        
        # Initialize biases as zeros. Shape: (1, n_neurons).
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        """
        Performs the forward pass calculation for this layer.
        
        Parameters:
        inputs (numpy.ndarray): The input data from the previous layer.
        
        Returns:
        numpy.ndarray: The output of the layer.
        """
        # Store the inputs for use in backpropagation later.
        self.inputs = inputs
        
        # Calculate the layer's output.
        # Output = (inputs • weights) + biases
        self.output = np.dot(inputs, self.weights) + self.biases
        
        return self.output

class Activation_ReLU:
    """
    A class representing the ReLU (Rectified Linear Unit) activation function.
    """
    def forward(self, inputs):
        """
        Performs the forward pass using the ReLU activation function.

        Parameters:
        inputs (numpy.ndarray): The input data (usually the output from a DenseLayer).

        Returns:
        numpy.ndarray: The activated output.
        """
        # Store the input for use in backpropagation later.
        self.inputs = inputs
        
        # Apply the ReLU function: output = max(0, input)
        self.output = np.maximum(0, inputs)
        
        return self.output
    
# --- Setup ---
# Create some random sample input data (e.g., 3 samples, 4 features).
sample_inputs = np.array([[ 0.7, -0.3,  0.1,  1.2],
                          [-0.5,  0.4, -0.9,  0.2],
                          [ 0.2,  0.5, -0.1, -1.8]])

# --- Create Layer Objects ---
# Create a dense layer with 4 input features and 5 neurons.
dense1 = DenseLayer(4, 5)

# Create a ReLU activation object.
activation1 = Activation_ReLU()

# --- Action: Perform the full forward pass for one hidden layer ---

# 1. Pass the data through the dense layer.
dense1.forward(sample_inputs)

print("--- Output of Dense Layer (Before Activation) ---")
print(dense1.output)

# 2. Pass the output of the dense layer through the activation function.
activation1.forward(dense1.output)

print("\n--- Output of Activation Layer (After ReLU) ---")
print(activation1.output)

--- Output of Dense Layer (Before Activation) ---
[[ 0.00856188  0.00386584  0.00757593  0.00907945 -0.00629516]
 [-0.01384743  0.00987859  0.01009158  0.01607266  0.0045663 ]
 [ 0.00454952 -0.0063972  -0.03007263 -0.02614391  0.00429693]]

--- Output of Activation Layer (After ReLU) ---
[[0.00856188 0.00386584 0.00757593 0.00907945 0.        ]
 [0.         0.00987859 0.01009158 0.01607266 0.0045663 ]
 [0.00454952 0.         0.         0.         0.00429693]]


In [6]:
import numpy as np

class DenseLayer:
    """
    A class representing a single, fully-connected (dense) layer in a neural network.
    
    KITCHEN ANALOGY: This is like a specialized workstation in our restaurant kitchen
    where multiple cooks (neurons) work simultaneously on the same customer orders,
    each following their own unique recipes (weights) and adding their secret ingredients (biases).
    """
    def __init__(self, n_inputs, n_neurons):
        """
        Initializes the layer's weights and biases.
        
        KITCHEN ANALOGY: This is like hiring and training workers when you first build the workstation.
        
        Parameters:
        n_inputs (int): The number of input features (ingredients coming to this station)
        n_neurons (int): The number of neurons in this layer (number of cooks at this station)
        """
        # Initialize weights with small random values. Shape: (n_inputs, n_neurons).
        # KITCHEN ANALOGY: Give each cook their own unique recipe card that tells them
        # how much of each ingredient to use. Start with small random amounts so
        # each cook specializes differently (if they all had the same recipe, 
        # they'd never learn to be unique!)
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        
        # Initialize biases as zeros. Shape: (1, n_neurons).
        # KITCHEN ANALOGY: Give each cook their own "secret ingredient jar" that starts empty.
        # Over time, they'll learn what special touch to add to make their dish unique.
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        """
        Performs the forward pass calculation for this layer.
        
        KITCHEN ANALOGY: This is when customer orders actually come in and 
        your kitchen station springs into action to process them!
        
        Parameters:
        inputs (numpy.ndarray): The input data from the previous layer (customer orders)
        
        Returns:
        numpy.ndarray: The output of the layer (dishes prepared by all cooks)
        """
        # Store the inputs for use in backpropagation later.
        # KITCHEN ANALOGY: Keep a copy of the customer order for quality control
        # and billing purposes - we might need to refer back to it later
        self.inputs = inputs
        
        # Calculate the layer's output.
        # Output = (inputs • weights) + biases
        # KITCHEN ANALOGY: Each cook follows their recipe (multiply ingredients by their weights)
        # and then adds their secret ingredient (bias). All cooks work on the same orders simultaneously.
        self.output = np.dot(inputs, self.weights) + self.biases
        
        return self.output

class Activation_ReLU:
    """
    A class representing the ReLU (Rectified Linear Unit) activation function.
    
    KITCHEN ANALOGY: This is your strict quality control inspector named "ReLU"
    who has one simple rule: "If a dish tastes bad (negative), throw it out and serve 
    nothing (0) instead. If it tastes good or neutral (positive/zero), serve it as-is."
    """
    def forward(self, inputs):
        """
        Performs the forward pass using the ReLU activation function.

        KITCHEN ANALOGY: The quality inspector examines each dish from every cook
        and decides whether to approve it for serving or reject it completely.

        Parameters:
        inputs (numpy.ndarray): The input data (dishes from the cooking station)

        Returns:
        numpy.ndarray: The activated output (approved dishes only)
        """
        # Store the input for use in backpropagation later.
        # KITCHEN ANALOGY: Keep a record of what dishes were inspected
        # in case we need to review the quality control process later
        self.inputs = inputs
        
        # Apply the ReLU function: output = max(0, input)
        # KITCHEN ANALOGY: ReLU Inspector's rule in action:
        # - Negative dish (tastes bad) → 0 (throw it out, serve nothing)
        # - Positive dish (tastes good) → keep as-is (serve the original dish)
        self.output = np.maximum(0, inputs)
        
        return self.output
    
# --- RESTAURANT SETUP ---
# KITCHEN ANALOGY: We're preparing to open our restaurant for the day!

# Create some sample customer orders (e.g., 3 customers, each ordering 4 ingredients)
# CUSTOMER ANALOGY: 
# Customer 1 wants: 0.7 flour, -0.3 eggs (less eggs), 0.1 milk, 1.2 sugar (extra sweet!)
# Customer 2 wants: -0.5 flour (less flour), 0.4 eggs, -0.9 milk (less milk), 0.2 sugar  
# Customer 3 wants: 0.2 flour, 0.5 eggs, -0.1 milk (slightly less), -1.8 sugar (much less sweet!)
sample_inputs = np.array([[ 0.7, -0.3,  0.1,  1.2],
                          [-0.5,  0.4, -0.9,  0.2],
                          [ 0.2,  0.5, -0.1, -1.8]])

# --- CREATE KITCHEN STATIONS ---
# KITCHEN ANALOGY: Now we're building and staffing our kitchen workstations!

# Create a cooking station with 4 ingredient inputs and 5 specialized cooks
# KITCHEN ANALOGY: This station can handle 4 different ingredients and has
# 5 cooks, each with their own unique recipes and secret ingredients
dense1 = DenseLayer(4, 5)

# Create our quality control inspector
# KITCHEN ANALOGY: Hire our strict inspector "ReLU" who will approve/reject
# each dish based on whether it tastes good (positive) or bad (negative)
activation1 = Activation_ReLU()

# --- RESTAURANT IN ACTION: Processing Customer Orders ---
# KITCHEN ANALOGY: The restaurant is now open and customers are placing orders!

# STEP 1: Send customer orders to the cooking station
# KITCHEN ANALOGY: All 3 customer orders go to our 5 cooks simultaneously.
# Each cook will prepare their version of each customer's order using their unique recipe.
dense1.forward(sample_inputs)

print("--- COOKING STATION OUTPUT (Before Quality Control) ---")
print("What our 5 cooks prepared for each customer:")
print(dense1.output)
print("\nShape:", dense1.output.shape, "→ (3 customers × 5 cooks)")

# STEP 2: Send the prepared dishes through quality control
# KITCHEN ANALOGY: Inspector ReLU examines every dish from every cook.
# Negative dishes get thrown out (→ 0), positive dishes get approved (→ kept as-is)
activation1.forward(dense1.output)

print("\n--- QUALITY CONTROL OUTPUT (After ReLU Inspection) ---")
print("What made it past the quality inspector:")
print(activation1.output)
print("\nShape:", activation1.output.shape, "→ (3 customers × 5 approved dishes)")

print("\n--- QUALITY CONTROL SUMMARY ---")
print("🔍 Inspector ReLU's decisions:")
for customer in range(3):
    original_dishes = dense1.output[customer]
    approved_dishes = activation1.output[customer]
    rejected_count = np.sum(original_dishes < 0)
    approved_count = np.sum(approved_dishes > 0)
    
    print(f"  Customer {customer + 1}: {approved_count}/5 dishes approved, {rejected_count}/5 rejected")

print("\n🏆 Complete kitchen station operational!")
print("✅ Cooking Station: 5 cooks with unique recipes")  
print("✅ Quality Control: ReLU inspector filtering bad dishes")
print("✅ Ready to connect to next kitchen station or serve customers!")

--- COOKING STATION OUTPUT (Before Quality Control) ---
What our 5 cooks prepared for each customer:
[[-0.00389273  0.02129566 -0.03759571  0.01000829  0.00774541]
 [-0.00769723  0.00573504  0.01367789 -0.00600109 -0.01034584]
 [-0.0063159  -0.03563661  0.01711868 -0.02927135 -0.02691469]]

Shape: (3, 5) → (3 customers × 5 cooks)

--- QUALITY CONTROL OUTPUT (After ReLU Inspection) ---
What made it past the quality inspector:
[[0.         0.02129566 0.         0.01000829 0.00774541]
 [0.         0.00573504 0.01367789 0.         0.        ]
 [0.         0.         0.01711868 0.         0.        ]]

Shape: (3, 5) → (3 customers × 5 approved dishes)

--- QUALITY CONTROL SUMMARY ---
🔍 Inspector ReLU's decisions:
  Customer 1: 3/5 dishes approved, 2/5 rejected
  Customer 2: 2/5 dishes approved, 3/5 rejected
  Customer 3: 1/5 dishes approved, 4/5 rejected

🏆 Complete kitchen station operational!
✅ Cooking Station: 5 cooks with unique recipes
✅ Quality Control: ReLU inspector filtering bad di